### PR TITLE
Fix #238 - Statistics growing with width

### LINKED ISSUE #238: Statistics on homepage with widescreen grows
image

It should stay the same size.

### PR DESCRIPTION
**Pull request by BenRauzi**
Resolve issue #238 
___
NB - by making a pull request you confirm agreement to the [Contributors Agreement](https://github.com/openlawnz/openlawnz-web/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by BenRauzi** [comment]
> Can you look at the .border class instead please
@williamparry 

Are you wanting there to be a visible border between the items or not? (There currently is not one on the live site unless you have a significantly lower resolution screen due to the way it's set up - the same error which is also causing the 'growing' of the box.) However if it is not required then these are not relevant.

**Comment by williamparry** [comment]
The margin of 2vw looks to be the thing stretching the box; please would you fix that, put the borders in and ensure it works on mobile?

**Comment by BenRauzi** [comment]
> The margin of 2vw looks to be the thing stretching the box; please would you fix that, put the borders in and ensure it works on mobile?
 @williamparry 

Yep it is, I've already made an update so give me a few minutes to push it.

**Comment by BenRauzi** [comment]
Have removed the 2vw width (which caused stretching and borders not to appear) and restored the borders, as well as adding borders for mobile as these were not previously there. (As per Figma designs)

**Pull request merged**
