### PR TITLE
Update Andrew photo

### PR DESCRIPTION
**Pull request by 300386357**

### CODE REVIEW

**Comment by 300386357** [comment]
> This is a big file. Could we reduce the image size and compress please?

Hi, I changed the images from png to jpg. Can you see the latest pull request?

**Comment by williamparry** [comment]
Thanks for that. The problem with jpg is that you'll lose the transparent background, meaning there will be a white box on the grey box of the tile.

**Comment by williamparry** [comment]
for now as a compromise let's put it back to png, make it the actual size (306px) and run it through a compressor e.g. https://tinypng.com/

**Comment by 300386357** [comment]
> for now as a compromise let's put it back to png, make it the actual size (306px) and run it through a compressor e.g. https://tinypng.com/

Thanks for telling me the compressor tool. It is useful.

**Pull request merged**
