### PR TITLE
CMS 'Drop-in' System

### PR DESCRIPTION
**Pull request by BenRauzi**
Allows different modules to be added under the same field in the CMS. (Under Microsite Sections.) The only module currently added is paragraphs.

One issue is that the heading of each one (when collapsed) will only show the name of the module, and not actually the title of the specific instance of that module. I'm currently trying to sort it out with some of the NetlifyCMS contributors.

@rb1193 Does this layout look good for you?
___
NB - by making a pull request you confirm agreement to the [Contributors Agreement](https://github.com/openlawnz/openlawnz-web/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by BenRauzi** [comment]
image
image

Allows you to add different widgets. (Only paragraph widget is currently added)

**Comment by rb1193** [comment]
Looks good to me! I didn't realise the beta features were already available in the cms, I was waiting on you to upgrade to a newer version or something :joy: 

I think looking at https://github.com/netlify/netlify-cms/blob/master/packages/netlify-cms-widget-list/src/ListControl.js#L362 you might be able to use the "summary" property to set the label?

**Comment by BenRauzi** [comment]
@rb1193 That's what I thought but it doesn't seem to work on items in a widget list for some reason.

Yeah same, turns out it was already in and just not recommended for use as it's a beta feature. The actual update taking it out of beta is soon though.

**Comment by rb1193** [comment]
Weird, might be worth opening an issue with Netlify if that's the case. Anyway, looks like it will be straightforward enough to integrate with the stuff I've done, I'll update my PRs once you've merged this

**Comment by BenRauzi** [comment]
Yeah I've jumped into their Slack server and have had a chat with them about it - it may require a manual configuration which is an issue I've seen before but not sure. I'll be doing that soon anyway so we'll see.

**Comment by BenRauzi** [comment]
All Widgets in the `modules` field should have a `title` string element.

**Pull request merged**
