### PR TITLE
Feature/adobe pdf viewer

### PR DESCRIPTION
**Pull request by caionnx**
Related to: #122 

To test it you'll need to create a `.env` file in the root of the project with the values I sent over Slack.
___
NB - by making a pull request you confirm agreement to the [Contributors Agreement](https://github.com/openlawnz/openlawnz-web/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by caionnx** [comment]
On hold waiting for the addition/allows of CORS

**Comment by caionnx** [comment]
@tehnools any impediments with the addition of CORS?

**Comment by caionnx** [comment]
@strum3nt all good to be merged? After this I will create a dedicated issue to research/implement IN_LINE mode as you mentioned.

@williamparry we'll need some help to set the env variables in production. Its critical and need to be done before deploy.

**Comment by strum3nt** [comment]
I'm happy for this to go live

**Pull request merged**
