### PR TITLE
Link to official legislation site from case info tab

### PR DESCRIPTION
**Pull request by gwkim8107**
Regarding issue #202, adding links to legislation references (visible in the info tab).
legislation_links

### CODE REVIEW

**Comment by strum3nt** [comment]
Looks good - have just removed extra slash from url

@gwkim8107 is keen to have a look to see if it is possible to link directly to section so will leave the pull request open for now

**Comment by gwkim8107** [comment]
> Looks good - have just removed extra slash from url
> 
> @gwkim8107 is keen to have a look to see if it is possible to link directly to section so will leave the pull request open for now

Now the links covered with the section area. Please check it whether the correction is right or not

**Comment by gwkim8107** [comment]
Hi, Andrew, this request is ready for review, please verify the issue has resolved.

**Comment by strum3nt** [comment]
@gwkim8107 great work!

Hey @caionnx I've tested the legislation and section links from a functionality perspective - it looks good to me. Can you review it from a code perspective please?

**Comment by williamparry** [comment]
Please fix merge conflicts.

**Comment by gwkim8107** [comment]
This PR should replace other PR.

**Pull request closed without merging**
